name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        pip install -r requirements.txt

    - name: Run Ruff Linter
      run: ruff check . --ignore E402,E501,F401,F403,F405,F841,E722 --show-source

    - name: Run Python Compile Check
      run: python -m compileall .
