name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with v (e.g. v1.5.260628)

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip repository
        run: |
          zip -r NarrativeOS.zip . -x "*.git*" "*scratch*" "*.venv*" "*__pycache__*" "*.ruff_cache*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: NarrativeOS.zip
          generate_release_notes: true
